export enum PromoValidationReason {
  EMPTY_CODE = 'EMPTY_CODE',
  INVALID_FORMAT = 'INVALID_FORMAT',
  NOT_FOUND = 'NOT_FOUND',
  INACTIVE = 'INACTIVE',
  EXPIRED = 'EXPIRED',
  FACILITY_MISMATCH = 'FACILITY_MISMATCH',
  USAGE_EXCEEDED = 'USAGE_EXCEEDED',
}
